Atnaujinta work package

diff --git a/packaging/scripts/backup b/packaging/scripts/backup
--- a/packaging/scripts/backup
+++ b/packaging/scripts/backup
@@ -64,18 +64,22 @@ else
   echo "* No Git repositories folder. Ignoring." >&2
 fi
 
-if [ -d "$ATTACHMENTS_STORAGE_PATH" ]; then
-  dst="${TARGET}/attachments-${timestamp}.tar.gz"
-  touch "$dst" && chmod 0640 "$dst"
-  echo -n "* Generating attachments backup..." >&2
-  if tar czf "$dst" -C "${ATTACHMENTS_STORAGE_PATH}" . ; then
-    echo " done" >&2
-    echo "$dst"
+if [[ $2 == "--skip_attachments" ]]; then
+  if [ -d "$ATTACHMENTS_STORAGE_PATH" ]; then
+    dst="${TARGET}/attachments-${timestamp}.tar.gz"
+    touch "$dst" && chmod 0640 "$dst"
+    echo -n "* Generating attachments backup..." >&2
+    if tar czf "$dst" -C "${ATTACHMENTS_STORAGE_PATH}" . ; then
+      echo " done" >&2
+      echo "$dst"
+    else
+      echo " failed" >&2
+    fi
   else
-    echo " failed" >&2
+    echo "* No attachments folder. Ignoring." >&2
   fi
 else
-  echo "* No attachments folder. Ignoring." >&2
+  echo "* Skipping attachments parameter found..." >&2
 fi
 
 if [ -d "/etc/${APP_NAME}/conf.d" ]; then
